const cardsStart = [
  ['Fruits 1', 'Fruits 2', 'Kitchen', 'Stationery', 'Vegetables', 'Verbs', 'School', 'Animals'],
  [
    {
      word: 'apple',
      translation: 'яблоко',
      image: './assets/fruits/apple.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'apricot',
      translation: 'абрикос',
      image: './assets/fruits/apricot.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'cherry',
      translation: 'вишня',
      image: './assets/fruits/Cherry.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'currant',
      translation: 'смородина',
      image: './assets/fruits/currant.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'grapefruit',
      translation: 'грейпфрут',
      image: './assets/fruits/grapefruit.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'grapes',
      translation: 'виноград',
      image: './assets/fruits/grapes.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'lemon',
      translation: 'лимон',
      image: './assets/fruits/lemon.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'lime',
      translation: 'лайм',
      image: './assets/fruits/lime.jpg',
      categories: 'Fruits 1',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'orange',
      translation: 'апельсин',
      image: './assets/fruits/orange.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'peach',
      translation: 'персик',
      image: './assets/fruits/peach.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'pear',
      translation: 'груша',
      image: './assets/fruits/pear.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'plum',
      translation: 'слива',
      image: './assets/fruits/plum.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'quince',
      translation: 'айва',
      image: './assets/fruits/quince.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'raspberry',
      translation: 'малина',
      image: './assets/fruits/raspberry.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'strawberry',
      translation: 'клубника',
      image: './assets/fruits/strawberry.jpg',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'watermelon',
      translation: 'арбуз',
      image: './assets/fruits/watermelon.webp',
      categories: 'Fruits 2',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'dish',
      translation: 'блюдо',
      image: './assets/kitchen/dish.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'fork',
      translation: 'вилка',
      image: './assets/kitchen/fork.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'kettle',
      translation: 'чайник',
      image: './assets/kitchen/kettle.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'knife',
      translation: 'нож',
      image: './assets/kitchen/knife.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'pan',
      translation: 'кастрюля',
      image: './assets/kitchen/pan.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'plate',
      translation: 'тарелка',
      image: './assets/kitchen/plate.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'spoon',
      translation: 'ложка',
      image: './assets/kitchen/spoon.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'tea set',
      translation: 'чайный сервиз',
      image: './assets/kitchen/tea-set.jpg',
      categories: 'Kitchen',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'elastic',
      translation: 'резинка',
      image: './assets/stationery/elastic.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'exercise book',
      translation: 'тетрадь',
      image: './assets/stationery/exercise-book.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'notebook',
      translation: 'блокнот',
      image: './assets/stationery/notebook.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'paintbrush',
      translation: 'кисть',
      image: './assets/stationery/paintbrush.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'paper',
      translation: 'бумага',
      image: './assets/stationery/paper.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'pen',
      translation: 'ручка',
      image: './assets/stationery/pen.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'pencil',
      translation: 'карандаш',
      image: './assets/stationery/pencil.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'ruler',
      translation: 'линейка',
      image: './assets/stationery/ruler.jpg',
      categories: 'Stationery',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'broccoli',
      translation: 'брокколи',
      image: './assets/vegetables/broccoli.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: './assets/vegetables/carrot.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'cucumber',
      translation: 'огурец',
      image: './assets/vegetables/cucumber.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'garlic',
      translation: 'чеснок',
      image: './assets/vegetables/garlic.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'onion',
      translation: 'лук',
      image: './assets/vegetables/onion.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'potato',
      translation: 'картофель',
      image: './assets/vegetables/potato.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'radish',
      translation: 'редис',
      image: './assets/vegetables/radish.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'tomato',
      translation: 'помидор',
      image: './assets/vegetables/tomato.jpg',
      categories: 'Vegetables',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'afraid',
      translation: 'испуганный',
      image: './assets/verbs/afraid.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'cry',
      translation: 'плакать',
      image: './assets/verbs/cry.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'go',
      translation: 'идти',
      image: './assets/verbs/go.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'laugh',
      translation: 'смеяться',
      image: './assets/verbs/laugh.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'look',
      translation: 'смотреть',
      image: './assets/verbs/look.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'run',
      translation: 'бежать',
      image: './assets/verbs/run.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'shout',
      translation: 'кричать',
      image: './assets/verbs/shout.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'show',
      translation: 'показывать',
      image: './assets/verbs/show.jpg',
      categories: 'Verbs',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'algebra',
      translation: 'алгебра',
      image: './assets/school/algebra.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'art',
      translation: 'изобразительное искусство',
      image: './assets/school/art.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'biology',
      translation: 'биология',
      image: './assets/school/biology.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'chemistry',
      translation: 'химия',
      image: './assets/school/chemistry.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'geography',
      translation: 'география',
      image: './assets/school/geography.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'geometry',
      translation: 'геометрия',
      image: './assets/school/geometry.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'history',
      translation: 'история',
      image: './assets/school/history.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'physics',
      translation: 'физика',
      image: './assets/school/physics.jpg',
      categories: 'School',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: './assets/animal/cat.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'crocodile',
      translation: 'крокодил',
      image: './assets/animal/crocodile.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './assets/animal/dog.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'duck',
      translation: 'утка',
      image: './assets/animal/duck.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'hare',
      translation: 'заяц',
      image: './assets/animal/hare.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: './assets/animal/mouse.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './assets/animal/pig.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
    {
      word: 'camel',
      translation: 'верблюд',
      image: './assets/animal/camel.jpg',
      categories: 'Animals',
      train: 0,
      playCorrect: 0,
      playIncorrect: 0,
    },
  ],
];

export default cardsStart;
